import { Link } from 'react-router-dom';
import { ArrowUpRight, CircleHelp } from 'lucide-react';
import { MAX_UPLOAD_MB } from '../../utils/uploadLimits';

const questions = [
  ['Which files can I upload?', `Use a text-based PDF or DOCX up to ${MAX_UPLOAD_MB} MB. Empty, damaged, password-protected, or image-only documents may not be readable. Scanned resumes need OCR before uploading.`],
  ['What happens to my resume?', 'CareerPilot extracts text for analysis and saves your resume and reports securely. If a hosted AI service is configured, your resume text is sent to that service for analysis; local processing keeps it on this machine.'],
  ['Why does analysis take time?', 'Generating detailed feedback can take a little time. If the service is busy, wait for the current request to finish before trying again.'],
  ['How should I use my ATS score?', 'Treat it as an estimate of alignment with a job description, not a guarantee of passing an employer’s system. Review missing requirements and only add skills or achievements you can truthfully support.'],
  ['Why was my document marked too long?', 'Current character limits are 8,000 for resume analysis; 8,000 resume / 5,000 job description for ATS and optimization. Shorten a copy and retry. The stored original is not changed.'],
  ['Can I compare ATS scores and export an optimized resume?', 'Yes. Apply only AI suggestions you can verify, or edit the draft directly. Compare ATS scores evaluates the original and saved draft for the same job description; a higher score is not guaranteed. Download updated resume saves current edits and exports a PDF. Word export is also available.'],
  ['How does the job tracker connect to ATS and optimization?', 'Save the exact job description, then link the resume and optional version used for that application. Opening ATS or Optimize from the application reuses that saved target. A newly generated optimized version is pinned back to the application, while status changes remain in its history.'],
  ['What appears in career analytics?', 'Analytics are calculated from your saved applications and resume versions: active applications by stage, roles that reached interview, follow-ups due in the next 14 days, recent status activity, and saved before/after ATS comparisons. Archived applications are counted separately.'],
  ['How does interview practice work?', 'Choose a saved application with a linked resume. CareerPilot generates technical, behavioral, and resume-specific questions from that resume and job description. Your typed answers, rubric scores, strengths, improvements, and follow-ups are saved so you can resume later. Displayed example answers repeat only your submitted facts and use placeholders where verified details are missing.'],
  ['What if my session expires?', 'CareerPilot attempts one secure refresh and queues requests that arrive at the same time. If the refresh cookie has expired or was revoked by logout, password reset, or account deletion, you are returned to sign in. Your saved work remains in your account.'],
  ['How do password reset emails work locally?', 'In local development, the server prints the single-use reset URL in its terminal when EMAIL_PROVIDER=console. A deployed app can use Resend. Reset links expire after the configured time and cannot be reused. The request page always shows the same response so it does not reveal whether an email is registered.'],
  ['What does deleting my account remove?', 'Account deletion permanently removes your profile, resumes, analyses, ATS reports, optimized drafts, job applications, and interview sessions. Cloudinary files are deleted immediately when possible; temporary storage failures are recorded and retried automatically.'],
  ['What should I try after an error?', 'For unreadable uploads, use a text-based PDF or DOCX. If an analysis takes too long or the service is busy, wait and retry once. For a network error, check your connection and try again. If a saved draft changed in another tab, refresh before saving again.'],
];

export default function HelpPage() {
  return <div className="workspace-help"><div className="overview-heading"><div><p className="eyebrow">A LITTLE GUIDANCE</p><h1>Help & support<span className="heading-dot">.</span></h1><p>Get the most out of your CareerPilot workspace.</p></div><CircleHelp size={28} className="text-brand-600" /></div><section className="workspace-panel help-questions">{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><div className="workspace-help-footer"><span>Ready to take the next step?</span><Link className="workspace-text-link" to="/dashboard/resume">Open resume studio <ArrowUpRight size={15} /></Link></div></div>;
}
