import { Link } from 'react-router-dom';
import { usePublicConfig } from '../hooks/usePublicConfig';
export default function PolicyPage({ kind }: { kind: 'privacy' | 'terms' | 'support' }) {
  const { data, isPending, isError } = usePublicConfig();
  return <div className="min-h-screen bg-[var(--paper)] px-5 py-12 text-[var(--ink)]"><article className="mx-auto max-w-3xl rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-6 sm:p-10">
    <Link to="/" className="text-sm text-[var(--accent)]">← CareerPilot</Link>
    <h1 className="mb-3 mt-7 text-3xl font-semibold">{kind === 'privacy' ? 'Privacy & AI data use' : kind === 'terms' ? 'Terms of use' : 'Support'}</h1>
    <p className="mb-7 text-sm text-[var(--muted)]">{data?.operator ? `Operated by ${data.operator}.` : 'Operator information has not been configured. This service is not ready for a public commercial release.'}</p>
    {kind === 'privacy' ? <div className="space-y-6 text-sm leading-7">
      <section><h2 className="font-semibold">What we store</h2><p>Your account profile, private uploaded files, extracted resume text, reports, editable drafts, job descriptions, applications, and interview answers are stored to provide your workspace. Passwords are hashed rather than stored as plain text.</p></section>
      <section><h2 className="font-semibold">AI processing and automatic fallback</h2><p>When you request AI feedback, relevant resume text, job descriptions, and submitted practice answers may be sent to the configured AI services. If automatic fallback is enabled, another listed AI service may receive the same content after a temporary failure. Only upload information you are authorized to share; avoid identity documents, financial details, or third-party confidential information.</p></section>
      <section><h2 className="font-semibold">Current data processors</h2>{isPending ? <p role="status">Loading the current configuration…</p> : isError ? <p role="alert">We could not verify the processor list. Do not submit personal data until it can be reviewed.</p> : <ul className="ml-5 list-disc">{data?.processors.map((processor) => <li key={processor}>{processor}</li>)}</ul>}<p className="mt-3">Processor retention and processing are governed by their applicable service agreements. Deleting CareerPilot records does not independently erase data retained by a processor under its own terms.</p></section>
      <section><h2 className="font-semibold">Retention, deletion and consent</h2><p>Workspace records remain until you delete them or your account. Interview history may retain a source-text snapshot after a source resume is deleted; delete the interview session or account to remove that history. Account deletion removes workspace records and queues stored-file deletion if storage is temporarily unavailable. Technical service counters expire automatically. Backup copies follow the operator’s configured retention schedule, which must be confirmed before commercial release.</p><p>You can withdraw AI processing agreement in account settings. This stops new AI requests but does not erase existing reports; delete those records separately.</p></section>
      <section><h2 className="font-semibold">Cookies</h2><p>A secure session cookie maintains sign-in. Access tokens remain in memory. Theme preferences are saved to your account and may also be saved on your device. No advertising trackers are implemented in this application.</p></section>
    </div> : kind === 'terms' ? <div className="space-y-6 text-sm leading-7">
      <p>CareerPilot assists with resume review, editing, application tracking, and interview practice. AI output may be incorrect. Review every suggested change and include only skills and achievements you can truthfully support.</p>
      <p>Scores are CareerPilot’s estimate of alignment—not an employer’s ATS result, hiring decision, certification, or guarantee of employment. You are responsible for reviewing exported documents before submitting them.</p>
      <p>You retain responsibility for and rights to the content you submit. Do not upload content you are not authorized to process, abuse the service, or attempt to access another person’s records. Usage and file limits may apply.</p>
      <p>Hosted AI use is intended for adults aged 18 or older. No paid subscription checkout is implemented. Any commercial pricing, cancellation, refund, and service-availability commitments must be published and reviewed by the operator before accepting payment.</p>
      <p>These operational terms and the privacy notice require operator/legal review for the intended markets. They are not a claim of legal compliance.</p>
    </div> : <p className="text-sm leading-7">For account, privacy, or technical help, {data?.supportEmail ? <a className="text-[var(--accent)] underline" href={`mailto:${data.supportEmail}`}>email {data.supportEmail}</a> : 'a public support contact still needs to be configured.'} Do not include passwords or API keys in support messages.</p>}
    <div className="mt-8 border-t border-[var(--line)] pt-5 text-sm">{data?.supportEmail && <a className="text-[var(--accent)] underline" href={`mailto:${data.supportEmail}`}>Contact the operator</a>}<nav className="mt-4 flex gap-5"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/support">Support</Link></nav></div>
  </article></div>;
}
